### ISSUE TITLE
Ability to `kick` auctions

### ISSUE THREAD

**Issue by reverendus** [makerdao/auction-keeper#2]
Currently `auction-keeper` only kicks in the moment the auction is already `kick`ed by somebody else.

I can imagine we could extend `auction-keeper` so that it monitors for example Dai surplus (for `flap`) or bad debt (for `flop`), if it sees that they are `>= lump` then it tentatively starts a model (null `id` will be passed to the model at that point, as they auction still doesn't exist so it doesn't have an `id` yet) and checks if the model outputs a `price`. If it does then it means the model wants us to bid, so we `kick` the auction and send our bid straight away.

After auction gets kicked we can either kill the old model and start a new one (this one will already get an `id`) or just pass the new `id` to the model we started tentatively, as long as we are able to identify that it is the same auction (can be done by comparing either `lot` or `bid` and/or `tab` in case of `flip`).

**Comment by EdNoepel** [comment]
Seems like `auction-keeper` already does this.  Also, modern versions of DSS automatically kick off the appropriate auction when a CDP is bitten or when `vow.flap` or `vow.flop` are invoked.
