### ISSUE TITLE
Provide valid price range(s) to the bidding model

### ISSUE THREAD

**Issue by reverendus** [makerdao/auction-keeper#5]
Currently if the bidding model wants to know the next minimal `price` it can bid, it needs to calculate it itself by multiplying the current `price` by `beg`. It gets a bit more complicated in the case of `flip` auctions as the `tend`-to-`dent` transition needs to be taken into account, possibly resulting in a condition which is more complicated than just `new_price >= min_price`.

I can imagine the keeper performing this calculation and providing valid `price` range(s) to the bidding model. It could be represented as:
```json
{
  "price": "1000.0",
  "validPrice": [["1050.0", null]]
}
```
or with two disjoint ranges in the case of `flip`:
```json
{
  "price": "1000.0",
  "validPrice": [["1050.0", "1200.0"], ["1260.0", null]]
}
```

**Comment by EdNoepel** [comment]
For `flip`s, the price offered by the model is implicitly translated into a `tend` and (if sufficiently high) `dent` bid.

The `beg` is passed to the model, and I find it perfectly reasonable for advanced price models to be responsible for their own price calculation.  Should this prove inadequate, or the model wishes to only participate in the `tend` or `dent` phase, it may be a sign that the user's strategy transcends the intent of `auction-keeper` and they should perhaps write their own bot.
