### ISSUE TITLE
Ability to pass arguments to the model

### ISSUE THREAD

**Issue by reverendus** [makerdao/auction-keeper#6]
Currently it's possible to run a model like that:
```bash
bin/auction-keeper \
    --model ../some-model.sh \
    [...]
```

but this doesn't work for some reason:
```bash
bin/auction-keeper \
    --model '../some-model.sh --price 750.0 --gas-price 10e9' \
    [...]
```

We should provide a way of passing custom commandline arguments to models as this will simplify deployment, especially in the case of simple static models where we could just pass the price as an argument. Otherwise a temporary script would have to be created each time.

**Comment by EdNoepel** [comment]
I fixed this using `nargs='+'` and joining the args.
